USE [master]
GO
/****** Object:  Database [MediWink]    Script Date: 16-12-2025 00:14:28 ******/
CREATE DATABASE [MediWink]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MediWink', FILENAME = N'C:\Users\avik2\MediWink.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MediWink_log', FILENAME = N'C:\Users\avik2\MediWink_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MediWink] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MediWink].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MediWink] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MediWink] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MediWink] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MediWink] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MediWink] SET ARITHABORT OFF 
GO
ALTER DATABASE [MediWink] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [MediWink] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MediWink] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MediWink] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MediWink] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MediWink] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MediWink] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MediWink] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MediWink] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MediWink] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MediWink] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MediWink] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MediWink] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MediWink] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MediWink] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MediWink] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MediWink] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MediWink] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MediWink] SET  MULTI_USER 
GO
ALTER DATABASE [MediWink] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MediWink] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MediWink] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MediWink] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MediWink] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MediWink] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MediWink] SET QUERY_STORE = OFF
GO
USE [MediWink]
GO
/****** Object:  Table [dbo].[DOC_LINK]    Script Date: 16-12-2025 00:14:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DOC_LINK](
	[LINK_ID] [numeric](6, 0) IDENTITY(10,1) NOT NULL,
	[PATIENT_ID] [numeric](5, 0) NOT NULL,
	[DOC_ID] [numeric](5, 0) NOT NULL,
	[LINK_DATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEDICINES]    Script Date: 16-12-2025 00:14:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEDICINES](
	[MED_ID] [numeric](5, 0) IDENTITY(1,1) NOT NULL,
	[MED_TYPE] [varchar](20) NOT NULL,
	[MED_NAME] [varchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NULL,
 CONSTRAINT [pk_medId] PRIMARY KEY CLUSTERED 
(
	[MED_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRESC_MEDICINE]    Script Date: 16-12-2025 00:14:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRESC_MEDICINE](
	[PRESC_MEDID] [numeric](5, 0) IDENTITY(1,1) NOT NULL,
	[PATIENT_ID] [numeric](5, 0) NOT NULL,
	[MED_ID] [numeric](5, 0) NULL,
	[DOSAGE] [char](2) NULL,
	[DURATION] [varchar](20) NULL,
	[FREQUENCY] [char](2) NULL,
	[REMARKS] [varchar](100) NULL,
 CONSTRAINT [pk_pRES_medId] PRIMARY KEY CLUSTERED 
(
	[PRESC_MEDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 16-12-2025 00:14:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[USERID] [numeric](5, 0) IDENTITY(10000,1) NOT NULL,
	[USER_TYPE] [char](1) NULL,
	[USER_NAME] [varchar](40) NOT NULL,
	[EMAIL] [varchar](100) NOT NULL,
	[PASSWORD] [varchar](50) NOT NULL,
	[CONTACT] [numeric](15, 0) NULL,
	[GENDER] [char](1) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[CREATED_BY] [varchar](20) NULL,
	[IS_ACTIVE] [char](1) NOT NULL,
 CONSTRAINT [pk_userId] PRIMARY KEY CLUSTERED 
(
	[USERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [uk_email] UNIQUE NONCLUSTERED 
(
	[EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOC_LINK] ADD  DEFAULT (getdate()) FOR [LINK_DATE]
GO
ALTER TABLE [dbo].[MEDICINES] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO
ALTER TABLE [dbo].[USERS] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO
ALTER TABLE [dbo].[USERS] ADD  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[PRESC_MEDICINE]  WITH CHECK ADD  CONSTRAINT [fk_medId] FOREIGN KEY([MED_ID])
REFERENCES [dbo].[MEDICINES] ([MED_ID])
GO
ALTER TABLE [dbo].[PRESC_MEDICINE] CHECK CONSTRAINT [fk_medId]
GO
ALTER TABLE [dbo].[PRESC_MEDICINE]  WITH CHECK ADD  CONSTRAINT [fk_patId] FOREIGN KEY([PATIENT_ID])
REFERENCES [dbo].[USERS] ([USERID])
GO
ALTER TABLE [dbo].[PRESC_MEDICINE] CHECK CONSTRAINT [fk_patId]
GO
ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [ck_gender] CHECK  (([GENDER]='O' OR [GENDER]='F' OR [GENDER]='M'))
GO
ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [ck_gender]
GO
ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [ck_usertype] CHECK  (([USER_TYPE]='P' OR [USER_TYPE]='D'))
GO
ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [ck_usertype]
GO
USE [master]
GO
ALTER DATABASE [MediWink] SET  READ_WRITE 
GO
