
USE MediWink


CREATE TABLE dbo.USERS (
	USERID NUMERIC(5) CONSTRAINT pk_userId PRIMARY KEY IDENTITY(10000,1),
	USER_TYPE CHAR(1) CONSTRAINT ck_usertype CHECK (USER_TYPE in ('D','P')),
	[USER_NAME] VARCHAR(40) NOT NULL,
	EMAIL VARCHAR(100) CONSTRAINT uk_email UNIQUE NOT NULL,
	[PASSWORD] VARCHAR(50) NOT NULL,
	CONTACT NUMERIC(15),
	GENDER CHAR(1) CONSTRAINT ck_gender CHECK (GENDER IN ('M','F','O')) NOT NULL,
	CREATED_DATE DATETIME DEFAULT GETDATE() NOT NULL,
	CREATED_BY VARCHAR(20),
	IS_ACTIVE CHAR(1) DEFAULT 1 NOT NULL


)

CREATE TABLE dbo.DOC_LINK (
	LINK_ID NUMERIC(6) CONSTRAINT pk_linkId PRIMARY KEY IDENTITY(10,1),
	PATIENT_ID NUMERIC(5) CONSTRAINT fk_patientId FOREIGN KEY (PATIENT_ID) REFERENCES USERS(USERID) NOT NULL,
	DOC_ID NUMERIC(5) CONSTRAINT fk_docId FOREIGN KEY (DOC_ID) REFERENCES USERS(USERID) NOT NULL,
	LINK_DATE DATETIME DEFAULT GETDATE() NOT NULL

)
 
CREATE TABLE MEDICINES (
	MED_ID NUMERIC(5) CONSTRAINT pk_medId PRIMARY KEY IDENTITY(1,1),
	MED_TYPE VARCHAR(20) NOT NULL,
	MED_NAME VARCHAR(50) NOT NULL,
	CREATED_DATE DATETIME DEFAULT GETDATE()
)

CREATE TABLE PRESC_MEDICINE (
	PRESC_MEDID NUMERIC(5) CONSTRAINT pk_pRES_medId PRIMARY KEY IDENTITY(1,1),
	PATIENT_ID NUMERIC (5) CONSTRAINT fk_patId FOREIGN KEY  (PATIENT_ID) REFERENCES USERS(USERID) NOT NULL,
	MED_ID NUMERIC(5) CONSTRAINT fk_medId FOREIGN KEY (Med_ID) REFERENCES MEDICINES(MED_ID),
	DOSAGE CHAR(2),
	DURATION VARCHAR(20),
	FREQUENCY CHAR(2),
	REMARKS VARCHAR(100) 

)
